query_url: "https://rest.uniprot.org/uniprotkb/stream?compressed=true&fields=accession%2Csequence%2Cec&format=tsv&query=%28reviewed%3Atrue+AND+ec%3A*+AND+length%3A%5B50+TO+1000%5D%29+AND+%28reviewed%3Atrue%29"

targets:
  0: 3000
  1: 2000
  2: 2000
  3: 1500
  4: 1500
  5: 1500
  6: 1500